### PR TITLE
Use 'swift_version' instead of 'pod_target_xcconfig{SWIFT_VERSION}' t…

### PR DESCRIPTION
**Pull request by dklinzh**
…o specify Swift version of pod target itself.

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ ] New extensions are written in Swift 4.
- [ ] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [ ] I have added tests for new extensions, and they passed.
- [ ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ ] All extensions are declared as **public**.
- [ ] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

### CODE REVIEW

**Comment by guykogus** [comment]
@LucianoPAlmeida any chance you can have a look into the travis issue? It feels like it should have been fixed by using cocopads beta, but either it's not being used or something else is going wrong. From what I've found the issue is this:
```
/var/folders/1c/ydg85g0n45d2s_x7pwptg1m80000gn/T/CocoaPods-Lint-20180926-22566-1iw2xml-SwifterSwift/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh: line 104: EXPANDED_CODE_SIGN_IDENTITY: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code
```
which from a basic Google search is showing a lot of people are having this problem with Xcode 10 and cocoapods.
Any idea how to resolve this? Do we need to do one of the hacks suggested by others facing this issue?

**Comment by LucianoPAlmeida** [comment]
@guykogus I'm taking a look on it :))

**Comment by guykogus** [comment]
@LucianoPAlmeida how did it suddenly pass? What changed?

**Comment by LucianoPAlmeida** [comment]
@guykogus 
Nothing changed 😆 🙃 
This is a weird issue that happens sometimes in the pod lib lint, just rebuild fixes it :))

**Comment by SD10** [comment]
Thank you for contributing to SwifterSwift! I've invited you to join the SwifterSwift GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md). Feel free to reach out if you have any questions! 😃

**Comment by LucianoPAlmeida** [comment]
@dklinzh Which version of CocoaPods are you using?

**Comment by dklinzh** [comment]
@LucianoPAlmeida I am using Cocoapods 1.5.3 now. @SD10 thanks for your invitation. 😄

**Comment by LucianoPAlmeida** [comment]
Humm @dklinzh thank you for the quick reply :))
We need to look at this a bit more, to me 
```ruby
s.pod_target_xcconfig = {
     'SWIFT_VERSION' => '4.2'
}
```
Should produce the same result as `s.swift_version='4.2'` and you wouldn't have the need to do this workaround.
I really don't know for sure and need to investigate this, so correct me if I'm wrong :)) 
I'll give you some feedback as soon as possible 👍 (probably the weekend 😅)

**Comment by dklinzh** [comment]
@LucianoPAlmeida I think [that](https://github.com/CocoaPods/CocoaPods/blob/299c319d1fb62a36022394476690beb161737e7a/lib/cocoapods/target/pod_target.rb#L99) is why the original `pod_target_xcconfig` doesn't work. The pod configuration of Swift version has been changed by the user target during `pod install`.

**Comment by LucianoPAlmeida** [comment]
humm I see 🤔 Thank you @dklinzh :))

**Comment by wdcurry** [comment]
What is the latest with this issue? I have been away from actively creating a new project for a few months (side gig as a script consultant) and trying to fire up a basic project, and always drop in SwifterSwift. 

Trying to stay close to current version, setting project to ios11.4, doing the usual, and seeing 31 compile errors.  My pod install is grabbing 4.4.0.

Is this enough info to glean my bad?

**Comment by guykogus** [comment]
@wdcurry you should be using 4.6.0

**Comment by wdcurry** [comment]
thanks, i will update to pod 'SwifterSwift', '~> 4.6.0'

**Pull request merged**
