### PR TITLE
Update README_CN.md 🚀

### PR DESCRIPTION
**Pull request by stavares843**
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ ] New extensions are written in Swift 5.0.
- [ ] New extensions support iOS 10.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [ ] I have added tests for new extensions, and they passed.
- [ ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ ] All extensions are declared as **public**.
- [ ] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

### CODE REVIEW

**Comment by guykogus** [comment]
@stavares843 why are you changing these links?

**Review by guykogus — CHANGES_REQUESTED** [review]
@stavares843 why are you changing these links?

**Comment by stavares843** [comment]
Captura de ecrã 2022-08-03, às 23 21 18
Captura de ecrã 2022-08-03, às 23 21 12

**Comment by stavares843** [comment]
https://github.com/SwifterSwift/SwifterSwift/pull/1030#issuecomment-1204835827

**Comment by stavares843** [comment]
👋

**Review by guykogus — APPROVED** [review]

**Pull request merged**
