### PR TITLE
Add unit tests for NSColor extensions #257 fix

### PR DESCRIPTION
**Pull request by LeLuckyVint**
Added tests for NSColor, renamed to ColorExtensionsTests

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 4.
- [x] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.

### CODE REVIEW

**Comment by LeLuckyVint** [comment]
Done, @omaralbeik!

**Comment by SD10** [comment]
Looks like we still have conflicts here. This looks like it's good to merge if we can get those resolved 👍

**Comment by LeLuckyVint** [comment]
@SD10, @omaralbeik, I've done this, but now we have 3 NSColor tests failed, but UIColor ones passed. Can you look into it?

**Comment by omaralbeik** [comment]
@LeLuckyVint Oh, I see, that's why unit tests are important 😅 
Will look at them soon.
Thanks :)

**Pull request merged**
