### PR TITLE
#312 Update travis to use xcode 9.1

### LINKED ISSUE #312: Update Travis to Xcode 9.1
https://docs.travis-ci.com/user/reference/osx/#xcode-91

### PR DESCRIPTION
**Pull request by kaphacius**
Closes #312 

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.

### CODE REVIEW

**Comment by kaphacius** [comment]
fails due to `[!] SwifterSwift did not pass validation, due to 29 warnings (but you can use `--allow-warnings` to ignore them).`

should i wait for #305 to be merged?

**Comment by omaralbeik** [comment]
Hey @kaphacius, please wait for #305 and #309 to be merged,

Thank you for taking care of this :)

**Comment by omaralbeik** [comment]
@kaphacius Please update from master to merge this PR :)

**Comment by kaphacius** [comment]
looks like the new image has a different tv os simulator name, have to change that as well

**Comment by omaralbeik** [comment]
Thanks @kaphacius!

**Pull request merged**
