### PR TITLE
Rename conflicting UIView extensions

### LINKED ISSUE #909: Ambiguous use of 'cornerRadius'
1. Found this candidate (AuthenticationServices.ASAuthorizationAppleIDButton)
2. Found this candidate (SwifterSwift.UIView)

### PR DESCRIPTION
**Pull request by Jayxiang**
Fixes #909 
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ ] New extensions are written in Swift 5.0.
- [ ] New extensions support iOS 10.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [ ] I have added tests for new extensions, and they passed.
- [ ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ ] All extensions are declared as **public**.
- [x] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

### CODE REVIEW

**Review by LucianoPAlmeida — COMMENTED** [review]
Code changes looks good, only missing changelog entry. Can you please add it under breaking changes? =]

**Review by LucianoPAlmeida — APPROVED** [review]
Thanks!

**Comment by guykogus** [comment]
I'm not really sure that I'm on board with changing `borderColor` and `borderWidth`, since according to the issue they come from other libraries. Do we really want to rename every name that clashes with another open source library? I get it if it clashes with one of Apple's own frameworks.

**Comment by LucianoPAlmeida** [comment]
> I'm not really sure that I'm on board with changing `borderColor` and `borderWidth`, since according to the issue they come from other libraries. Do we really want to rename every name that clashes with another open source library? I get it if it clashes with one of Apple's own frameworks.

The way I see is more a way to improve the expressivity of the names(since all are abstractions to change layer properties, I like having `layer` prefix to make that clear) than fix collision issues since, the new name may colide as well... So at the I'm good with this change because of that, fixing collision is just a bonus =]

**Review by guykogus — APPROVED** [review]

**Pull request merged**
