### PR TITLE
Add new Array & Date extensions

### PR DESCRIPTION
**Pull request by SD10**
Summary of Pull Request:

Add new **Array** extensions
`func forEach(where condition: (Element) -> Bool, body: (Element) -> Void)`
`func take(while condition: (Element) -> Bool) -> [Element] `
`func skip(while condition: (Element) -> Bool) -> [Element]`
`mutating func keep(while condition: (Element) -> Bool)`
`mutating func drop(while condition: (Element) -> Bool)`

Add new **Date** extensions
`isInWeekday`

### CODE REVIEW

**Comment by omaralbeik** [comment]
@SD10 Great job as usual 🥇

**Comment by SD10** [comment]
Thank you @omaralbeik. 
Next PR I have to increase the update the tests to hit the default case. I missed 3 lines 😃

**Comment by omaralbeik** [comment]
@SD10 
link

**Comment by SD10** [comment]
This Slack integration is great. I can read everything that's happening in the repo 👍

**Pull request merged**
