### PR TITLE
fixed "".truncated crashed

### PR DESCRIPTION
**Pull request by philCc**
fixed Fatal error: Can't form Range with upperBound < lowerBound

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
@philCc Can you add a changelog entry for this as well? :)

**Comment by philCc** [comment]
> @philCc Can you add a changelog entry for this as well? :)

I'm sorry, I don't know where to add.

**Comment by LucianoPAlmeida** [comment]
> > @philCc Can you add a changelog entry for this as well? :)
> 
> I'm sorry, I don't know where to add.

You can take a look at this :)
https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md#adding-changelog-entries
Or check-in previous merged PRs to see how others have done it :)

**Comment by philCc** [comment]
It has been added and the changelog format error has been modified

**Comment by SD10** [comment]
Thank you for contributing to SwifterSwift! I've invited you to join the SwifterSwift GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md). Feel free to reach out if you have any questions! 😃

**Pull request merged**
