### PR TITLE
Added stablePartition by condition array method

### PR DESCRIPTION
**Pull request by neoneye**
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 4.
- [x] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [x] I have added a changelog entry describing my changes.

### CODE REVIEW

**Comment by neoneye** [comment]
This function is inspired by Ruby's `partition` function, http://ruby-doc.org/core-2.5.0/Enumerable.html#method-i-partition

The name `partition` is already taken by Swift Array class. The second best name I could come up with is: `stablePartition`, since the element ordering is preserved.

**Comment by neoneye** [comment]
I'm not a native english speaker, so I don't know.

Your name `divided(by:)` is great. 

Ideas for other names: `separate`, `split`, `order`.

**Comment by neoneye** [comment]
@LucianoPAlmeida I just added parameter names to the returned tuple. Perhaps this is helpful to some users. I can't think of more things. I think it's ready for merge.

**Comment by neoneye** [comment]
@LucianoPAlmeida wait a little. I'm considering moving it to the `Collection` extension.

**Comment by neoneye** [comment]
Olà @LucianoPAlmeida 

The current `Array.divided(by:)` in `ArrayExtension` has simple and short tests, easy to understand. I think the PR as it is now is good.

I have made a [collection-dividedby](https://github.com/neoneye/SwifterSwift/commits/collection-dividedby) branch. Here the `Collection.divided(by:)` has unfortunately [complicated the tests](https://github.com/neoneye/SwifterSwift/blob/collection-dividedby/Tests/SwiftStdlibTests/CollectionExtensionsTests.swift#L28). I doubt anyone will ever use it for splitting dictionaries/strings. I think Arrays is the primary usecase.

Perhaps you can decide if you want it in the `ArrayExtension` or the `CollectionExtension` ?

**Comment by LucianoPAlmeida** [comment]
@neoneye I agree that Array is the primary use case, so maybe it's enough to let it just as an Array extension :)

**Pull request merged**
