### PR TITLE
Fix testInitAsyncThrows

### LINKED ISSUE #1156: Cannot build `FutureExtensionsTests` in Xcode 15.1
🚀
**Describe the bug**
Hello.
Thank you for SwifterSwift.
Found out that I cannot build `FutureExtensionsTests` (I added this class to the project).

**To Reproduce**
1. Open **SwifterSwift.xcworkspace** in Xcode 15.1.
2. Select **SwifterSwift-macOS** target.
3. Run **Product** -> **Test**.
4. Getting **'self' is not a member type of protocol 'Swift.Error'** in `testInitAsyncThrows`.

**Expected behavior**
Tests are running.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 14.1.2

- [x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### PR DESCRIPTION
**Pull request by RomanPodymov**
🚀
Hello.
Thank you for SwifterSwift.
Fix #1156.
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 5.6.
- [x] New extensions support iOS 12.0+ / tvOS 12.0+ / macOS 10.13+ / watchOS 4.0+, or use `@available` if not.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [ ] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

### CODE REVIEW

**Comment by guykogus** [comment]
@RomanPodymov what are you changing here? It mostly looks like swiftformat changes, and I think you're on the wrong version or something. Please pull the latest `master` branch and install the latest version of swiftformat. You shouldn't have any changes.

**Comment by RomanPodymov** [comment]
Hello @guykogus 
Merged `master` to my branch, but see the same changes.

**Comment by guykogus** [comment]
@RomanPodymov if you pull the latest `master` branch of SwifterSwift and run `swiftlint` and `swiftformat`, you'll see no warnings and no changes. What versions are you running? Can you please check `swiftlint --version` returns `0.53.0` and `swiftformat --version` returns `0.52.11`?

**Comment by guykogus** [comment]
Closing, unless you can help me understand what is being fixed here and why the formatting has changed?

**Pull request closed without merging**
