### PR TITLE
Created Array.random Extension Method

### PR DESCRIPTION
**Pull request by calebkleveter**
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 4.
- [x] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [x] I have added a changelog entry describing my changes.

### CODE REVIEW

**Comment by calebkleveter** [comment]
Guess I didn't look hard enough 😂. But according to the [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/#naming), shouldn't it be named `Collection.random`? Not sure, that's why I am asking 🙂.

**Comment by LucianoPAlmeida** [comment]
Hey @calebkleveter 
Since we talking about collections it makes more sense:
```swift
collection.randomItem // "Collection have, give me a random item"
collection.random // "Collection, give me a random? A random what? Is this something to randomize  the collection items and returning?"
```
I think `randomItem` is more clear and fluent :) 
But it's just a personal opinion and how I interpreted the guidelines, I'm also not 100% sure 😂😂

**Comment by akuzminskyi** [comment]
In both(the PR and master) have an issue, what of we have an empty array. In both cases will be a crash out of range. I think that we should mark output parametr as Optional 
`public var randomItem: Iterator.Element?`
What do you think?

**Comment by SD10** [comment]
@akuzminskyi Good catch, this should return an `Element?` 👍 Feel free to open a PR

**Comment by LucianoPAlmeida** [comment]
@akuzminskyi Good catch :) 
@SD10 I just opened an issue #404 for this

**Pull request closed without merging**
