### PR TITLE
Fix Comparable extensions to used `ClosedRange` vs `min/max`.

### PR DESCRIPTION
**Pull request by freak4pc**
Fixes concerns raised in #466. 

Didn’t add a CHANGELOG since its a recent addition but LMK if its needed.

### CODE REVIEW

**Comment by freak4pc** [comment]
IRT to the first method, I think it might be more explicit to have `isBetween` but if you think the standard `range` syntax is sufficient, I can get rid of it

**Comment by SD10** [comment]
I thought about this when reviewing the initial PR but didn’t want to make the extension dependent on the range type. My use case was comparing two custom `Comparable` types that are not ranges. Am I missing something? cc @LucianoPAlmeida

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LucianoPAlmeida** [comment]
Hey @SD10  :)) 
Range types are bounded to comparable. So you can create any range type (Range, ClosedRange, PartialRangeTo... and so on) with any custom type since this type conforms to comparable. I mean the only requirement to create a range with a type is this type to be comparable, so basically, any comparable can be made a range :)) 
I did a blog post a few months ago about range types in general, you can see [here](https://medium.com/@lucianoalmeida1/exploring-range-types-in-swift-e0e7ab27ab79) with more details.

**Comment by freak4pc** [comment]
@LucianoPAlmeida except for `ClosedCountableRange`, which also needs `Strideable` :)

**Comment by SD10** [comment]
@LucianoPAlmeida so if I have a `User` model that conforms to `Comparable`, I can just write this?
```swift
struct User: Comparable {}
let usr1 = User()
let usr2 = User()
usr1...usr2 // <-- this is valid?
```

**Comment by freak4pc** [comment]
@SD10 Yes it is :) 

003a88e0-b233-4781-840b-ab7770d4fb0b

**Comment by LucianoPAlmeida** [comment]
@SD10 Sure, this is valid :))
@freak4pc  That's right `CountableClosedRange`has Stridable requirements :))

**Comment by SD10** [comment]
iiiiiinteresting 🙃 I feel like I just learned something great. Thanks guys!

**Comment by LucianoPAlmeida** [comment]
@freak4pc  About `isBetween` I agree that is more explicity :)) 
I have a proposal maybe for a future extension, to have something like
```swift
extension Comparable {
    func isBounded<R: RangeExpression>(to range: R) -> Bool where R.Bound == Self {
        return range.contains(self)
    }
}
// Can support all ranges
5.isBounded(to: 5...)
6.isBounded(to: 5...10)
7.isBounded(to: 5..<10)
6.isBounded(to: ...5)
```
I don't  mean to replace `isBetween` because is between naming makes total sense to receive a ClosedRange :))

**Comment by freak4pc** [comment]
@LucianoPAlmeida I like that idea ! Definitely worth having.

**Pull request merged**
