### PR TITLE
Swap index position array extension.

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/omaralbeik/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] I have **only one commit** in this pull request.
- [x] New extensions support iOS 8 or later.
- [x] New extensions are written in Swift 3.
- [x] I have added tests for new extensions, and they passed.
- [x] Pull request was created to [**master head branch**](https://github.com/omaralbeik/SwifterSwift/tree/master).
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All comments headers have the word **SwifterSwift:** before description.

### CODE REVIEW

**Comment by SD10** [comment]
Hey @LucianoPAlmeida,
Thank you for the PR!

I think this functionality already be accomplished with the use of:
```swift
var array = [1, 2, 3]

swap(&array[0], &array[2])
```
Was your intent to give this action a new interface or make it a fail safe operation?

I prefer operations that require Index math to fail as you should have already thought carefully about the logic so that your index is never out of range. 

I think this is why Array's have the behavior they do.

Please let me know your thoughts!

**Comment by omaralbeik** [comment]
@LucianoPAlmeida @SD10 How about we change the name to `safeSwap` ?
and @LucianoPAlmeida maybe consider separating the condition in the guard statement to multiple guards, it reads better

Thank you for your contribution, keep the great work!

**Comment by SD10** [comment]
I agree @omaralbeik `safeSwap` would be a great name for this.

I'd also like to base the implementation off using the `startIndex` rather than 0 in case we refactor the extensions to support other types such as `ArraySlice` in the future.

Possibly something like this:

```swift
extension Array {

    public mutating func safeSwap(from index: Int, to otherIndex: Int) {
    
        guard index != otherIndex,
              startIndex...endIndex ~= index,
              startIndex...endIndex ~= otherIndex else { return }
        
        Swift.swap(&self[index], &self[otherIndex])
    
    }
} 
```

**Comment by LucianoPAlmeida** [comment]
Hello @omaralbeik @SD10 
Thank you for the feedback :)

Answering @SD10 's both new interface and make it safe were the intentions for this, but the main one was to give a new interface since i think it's more readable, simple and more swift 3 like API. 

I agree with the name change to safeSafe since make swap operation safe was one of the intentions when i thought this extension. But i also think in keep implementation of swap without safe check just as a simpler interface for ` Swift.swap(&array[index], &array[otherIndex]) `. 

Please let me know your thoughts :)

**Comment by omaralbeik** [comment]
That makes sense to me
Thank you @LucianoPAlmeida!

**Comment by SD10** [comment]
Great work, thank you @LucianoPAlmeida

**Pull request merged**
