### PR TITLE
Add base64String methods to UIImage

### LINKED ISSUE #742: Add base64String extension to UIImage
Add a `base64String` property to return the encoded image as a base 64 string

```swift
public extension UIImage {
    /// SwifterSwift: Base 64 representation of the image.
    var base64String: String? { ... }
}
```

### PR DESCRIPTION
**Pull request by moritzsternemann**
🚀 Base64-encode a `UIImage`s `pngData()` and `jpegData(compressionQuality:)` and return it as a string.

Resolves #742 

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 5.0.
- [x] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [x] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
I think we forget about this one 😅, sorry @moritzsternemann 
If we take too much time to give at least an `l'll review asap` comment, feel free to ping us :)

**Comment by guykogus** [comment]
@LucianoPAlmeida this is marked as Work-In-Progress because we never concluded the discussion in https://github.com/SwifterSwift/SwifterSwift/issues/742

**Comment by LucianoPAlmeida** [comment]
Oops, sorry @guykogus I didn't see the WIP 😅 
Thank's for pointing out :))

**Comment by moritzsternemann** [comment]
@guykogus @LucianoPAlmeida I updated the PR, it's now ready for review 😄

**Pull request merged**
