### PR TITLE
Update docstrings for static colors

### PR DESCRIPTION
**Pull request by pvtmert**
as requested

### CODE REVIEW

**Comment by SD10** [comment]
@pvtmert Thanks for doing this 😃 🎉

**Comment by pvtmert** [comment]
@SD10 actually *nix did it for me, here is generator script
```
#!/usr/bin/env bash

test -z "$1" && {
	echo "param required"
	exit 1
}

(test "${1:0:4}" == "http" && curl -s "$1" || cat "$1") | awk '{
	FS="\\s+= (NS|UI)Color\\(hex: 0x"
	if( match($0, FS) ) {
		print "\n\t\t// SwifterSwift: hex #" substr($2, 1, 6)
	}
	if( match($0, "public static let [a-zA-Z]+\\s+= [a-z0-9]+") ) {
		split($0, CLR, "\\s+=\\s+")
		print "\n\t\t// SwifterSwift: color", CLR[2]
	}
	print $0
}'
```

**Comment by SD10** [comment]
@pvtmert I could learn a thing or two from you 😅. Please squash this when you merge!

**Comment by pvtmert** [comment]
@SD10 actually @omaralbeik will review merge, you should see C macros :)

**Comment by pvtmert** [comment]
So, @omaralbeik updated even further according to [Contributing Guidelines (v3)](/tree/v3/CONTRIBUTING.md). closing...

**Comment by omaralbeik** [comment]
Brilliant job @pvtmert, saved us lots of work, I added the new NSColorExtensions.swift & UIColorExtensions.swift files

**Pull request closed without merging**
