### PR TITLE
Closes #298 Date.year not working properly

### LINKED ISSUE #298: Date.year not working
[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
I used Date.year extension to update year component of a date.

### What did you expect to happen?
year component to be changed.

### What happened instead?
Year didn't change.

### SwifterSwift Environment
- SwifterSwift version: **4.0.1**
- Xcode version: **9.0.1**
- macOS version running Xcode: **High Sierra**
- Swift version: **4.0**
- Platform(s) running SwifterSwift: **iOS**

### Demo Code
```
var date = Date()
print("Year before change: \(date.year)") // "Year before change: 2017"
date.year = 2010
print("Year after change: \(date.year)") // "Year after change: 2017", should be 2010
```

### PR DESCRIPTION
**Pull request by kaphacius**
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 4.
- [x] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.

### CODE REVIEW

**Comment by buddax2** [comment]
I would add at least one negative test like:
```
date.year = 2017
XCTAssertTrue(date.year, 1988)
```

**Comment by SD10** [comment]
@kaphacius If you could also add a CHANGELOG entry this would be great

**Comment by kaphacius** [comment]
okay, that's interesting. the test works fine on my machine, on mac os scheme. maybe different versions of mac os?
@SD10 i'll look into CHANGELOG, never done that

**Comment by LucianoPAlmeida** [comment]
Hey @kaphacius it breaks here on my machine too.
screen shot 2017-10-27 at 20 27 24

**Comment by kaphacius** [comment]
@LucianoPAlmeida that's interesting. what sdk/mac os are you running?

**Comment by LucianoPAlmeida** [comment]
@kaphacius I'm on MacOS Sierra 10.12.6, Xcode9.0.1(9A1004). Just the normal stack. :)

**Comment by kaphacius** [comment]
@LucianoPAlmeida okay, that's strange. I'm on Xcode 9.0 and High Sierra 10.13 and it works for mine. I wanted to try with an older base SDK, downloaded it from [here](https://github.com/phracker/MacOSX-SDKs) but Xcode gives me a build error 

> Swift does not support the SDK 'MacOSX10.12.sdk'

any suggestions?

**Comment by omaralbeik** [comment]
@LucianoPAlmeida @kaphacius Not sure why this is happening 🤔 , it makes me wonder if there is a better way to set date components

**Comment by LucianoPAlmeida** [comment]
@omaralbeik I really don't know if there are other ways, the guy of the issue on the other repo I mentioned in the [#298](https://github.com/SwifterSwift/SwifterSwift/issues/298) tried some ways that also didn't work.

**Comment by kaphacius** [comment]
@LucianoPAlmeida @omaralbeik the current way gives a nice error handling (setting day to a negative value / more than 31 keeps the previous value), same with seconds/hours/minutes etc works for other components. maybe it's better if we can figure it out why it fails on SDK 10.12

**Comment by kaphacius** [comment]
so if someone could check out my pr and make appropriate changes that would be great, since i can't compile it under 10.12 sdk

**Comment by omaralbeik** [comment]
Of course, I'll take care of it this weekend, Thank you @kaphacius 👍

**Comment by omaralbeik** [comment]
Travis is now happy :) however I think Date extensions need a complete rewrite and more tests 🤔

**Pull request merged**
