### PR TITLE
SPM (Swift Package Manager) was throwing error

### PR DESCRIPTION
**Pull request by ratulSharker**
…nd resources will be in a directory and the directory name should ends with `Tests`. Here `SwifterSwiftTests.swift` was at root & resouce container directory name was `Resource`. So Placing the `SwifterSwiftTests.swift` inside a directory named `SwifterSwiftTests` and `Resource` folder is renamed to `ResourceTests` solved the problem.

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ ] New extensions are written in Swift 4.
- [ ] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [ ] I have added tests for new extensions, and they passed.
- [ ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ ] All extensions are declared as **public**.
- [ ] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) 

While adding **SwifterSwift** as Swift package using SPM (Swift Package Manager), the dependencies resolved perfectly. But the process generating the `xcodeproj` file throws some error

My `Package.swift` file

```swift
import PackageDescription

let package = Package(
    name: "Learning Perfect",
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/PerfectlySoft/Perfect-HTTPServer.git", from: "3.0.0"),
        .package(url: "https://github.com/SwifterSwift/SwifterSwift.git", from: "4.4.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages which this package depends on.
        .target(
            name: "Learning Perfect",
            dependencies: ["PerfectHTTPServer", "SwifterSwift"]),
    ]
)
```

when i run `swift package update`, it resolves the dependencies, but generating the xcodeproj file was throwing error

```bash -- update here
swift package generate-xcodeproj
'SwifterSwift' /Users/ratulsharker/Desktop/Learning/Learning Perfect/.build/checkouts/SwifterSwift.git--7830422156731560571: error: package has unsupported layout; found loose source files: /Users/ratulsharker/Desktop/Learning/Learning Perfect/.build/checkouts/SwifterSwift.git--7830422156731560571/Tests/SwifterSwiftTests.swift
'Learning Perfect' /Users/ratulsharker/Desktop/Learning/Learning Perfect: error: product dependency 'SwifterSwift' not found
```

So i moved the `SwifterSwiftTests.swift` to a folder `SwifterSwiftTests`, Then it was throwing another error, while generating the xcodeproj, which look like following

```bash
swift package generate-xcodeproj
'SwifterSwift' /Users/ratulsharker/Desktop/Learning/Learning Perfect/.build/checkouts/SwifterSwift.git-3894317342873169084: error: invalid target name at 'Tests/Resources'; name of test targets must end in 'Tests'
```

After that i renamed the `Tests/Resources` as `Tests/ResourcesTests`. Finally the errors were gone.

Finally an warning is generated while i created the xcodeproj

```bash
swift package generate-xcodeproj
generated: ./Learning Perfect.xcodeproj
warning: target 'ResourcesTests' in package 'SwifterSwift' contains no valid source files
```

I hope we can ignore that for now, because SPM (Swift Package Manager) is still in it's early stage. Any suggestion in about resolving this warning is welcome. I just don't have any idea that, it will be un-conventional or not to put these resources using for tests in project root directory is okay or not, for the sake of the warning message.

### CODE REVIEW

**Comment by ratulSharker** [comment]
Thanks @omaralbeik 

But i doubt that, SPM will approve that ☹️. Let me do a little check on that and i will let you know.

**Comment by ratulSharker** [comment]
Hi @omaralbeik 

Sorry for my late response. As per suggestion i tested for the `TestResources` but still SPM was throwing the same error as  earlier. So i reverted the folder name to  `ResourcesTests`.

After successful package update & generating the `xcodeproj`, i was facing some import related error. For the Swift standard library extensions,  there are several files i have found which requires `Foundation` import missing with the `canImport` check on it. 

I adde those missing `import Foundation` with the `canImport` check and also put `canImport` check where usage of these Foundation feature are used.

For now i have only check SPM integration for mac os only, not for the linux os. Hope there will be little to do for linux.

If you want to check the integrity of the SPM, 

try following for the version where `swift package update` & `swift package generate-xcodeproj` both will succeed but the generated project won't compile, because of the  missing `import Foundation` related problems.

```swift
...
...
...
.package(url: "https://github.com/ratulSharker/SwifterSwift.git", from: "4.4.3")
...
```

try following for the version where everything is stable for now (macos).

```swift
...
...
...
.package(url: "https://github.com/ratulSharker/SwifterSwift.git", from: "4.4.5")
...
```

**Comment by ratulSharker** [comment]
Another thing i forgot to mention, i have updated the required swift tool version to 4.0, otherwise few extension were throwing error like 

**Code**
```swift
// NSImageExtensions.swift
public func write(to url: URL, fileType type: NSBitmapImageRep.FileType = .jpeg, compressionFactor: NSNumber = 1.0)
```

**Error Message** 

> jpeg has been renamed to JPEG

This line was throwing error saying that there is no case declared like `.jpeg` available options were `.JPEG` which was declared in swift 3.0.

**Comment by omaralbeik** [comment]
Thank you @ratulSharker

**Pull request merged**
