### PR TITLE
add semicolons to lastIndex(of:) and firstIndex(of:) doc

### PR DESCRIPTION
**Pull request by zinthemoney**
## Checklist

- [x ] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ ] New extensions are written in Swift 4.
- [ ] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [ ] I have added tests for new extensions, and they passed.
- [ ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ ] All extensions are declared as **public**.

### CODE REVIEW

**Comment by wdcurry** [comment]
May i ask why firstIndex is deprecated? It is the simplest of checks, is logical, is intuitive. Flipping to a StringProtocal and range is just overkill, like numerous other Swift "improvements". Loving the language for the most part, but it is starting to become a bit "mySpace-y" in some areas.

**Comment by guykogus** [comment]
I'm guessing it's because using `Int`s for the indices of characters in a `String` is a bad idea, that's not how `String`s are built anymore. You should be using `String.Index` values instead, which is what's provided by the functions mentioned in the deprecation message.
I'm open to being convinced otherwise. What's your use case where you need these functions?

**Comment by wdcurry** [comment]
Fair enough, I still do strings old-school, learning to remap my brain a bit. Funny i rely on SwifterSwift so much that i forget to check and just pushed String.contains() into my code for a simple Bool return, which works well, apart from a few minor edits. I should have found that before asking ;)

**Comment by SD10** [comment]
https://developer.apple.com/documentation/swift/string/2997120-firstindex?changes=latest_minor

It's part of the Swift Standard Library now

**Pull request merged**
