### PR TITLE
Add stack function to array with element UIView

### PR DESCRIPTION
**Pull request by BennX**
Adding the function to create a UIStackView from an Array of UIViews. Taking the defaults and parameter docs from Apples Defaults.

Solves #399

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 4.
- [x] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [x] I have added a changelog entry describing my changes.

### CODE REVIEW

**Comment by LucianoPAlmeida** [comment]
Hey @BennX Thank you for taking your time to make this PR
The implementation seems nice, btw great tests 👍 
But some points I think is worth to discuss: 
* Although this is an Array extension, to me it feels like the ArrayExtensions is not the right place for this because it is the stdlib and this kinda inserts the UIKit dependency on something that is from stdlib.
* Another option for this could be convenience init on UIStackview that contains these parameters like:
```swift 
convenience init(arrangedSubviews: [UIView], orientation: UILayoutConstraintAxis = .horizontal, spacing: CGFloat = 0.0, alignment: UIStackViewAlignment = .fill, distribution: UIStackViewDistribution = .fill)
```    
What do you guys think? @BennX @SD10 @omaralbeik

**Comment by BennX** [comment]
@LucianoPAlmeida I actually like the idea of having it as extension to an Array.

Since it will only exists if the Array is typed with UIView it wont extend every array and therefore only adds UIKit dependencies for that kind of array. Swift generics are on compile time therefore we should be good.

Having a convenience init on UIStackView is a good option too but for me it wont feal that `Swifty` to use a regular constructor for stacking a list. It feels like having a `sort(array:)` instead of a `array.sort`.

**Comment by LucianoPAlmeida** [comment]
For sure @BennX totally agree, just point the convenience as an option :)
My main concern here is the first point, because of coupling dependency at a module level. I mean there's no problem in using generic constraints, in fact it is great, but to me the problem is where (in what module) this extension is defined, since we use subspecs to define the Stdlid extensions, UIKit ... and other modules. So defining a extension on a file of stdlib module that uses a type from uikit, makes the Stdlib module have a dependency on uikit module. That's what I mean with "dependency", btw sorry for the bad explanation on the first comment 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
@BennX How often do you have an array of `UIView` laying around to initialize a `UIStackView`?
I usually just create them 1 by 1:
```Swift
let btn = UIButton()
let sgmt = UISegmentedControl()
let view = UIView()
let stackView = UIStackView(views: [btn, sgmt, view])
```
Having to put them in an `Array` first feels kind of weird 🤔

**Comment by calebkleveter** [comment]
If you where to implement an initializer, you could probably write it like this:
```swift
extension UIStackView {
    public init(views: [UIView], orientation: UILayoutConstraintAxis = .horizontal, spacing: CGFloat = 0.0, alignment: UIStackViewAlignment = .fill, distribution: UIStackViewDistribution = .fill) {
        self = views.stacked(orientation:, orientation, spacing: spacing, alignment: alignment, distribution: distribution)
    }
}
```

I don't know if you can do `self =` in a `UIStackView` init though.

**Comment by SD10** [comment]
@calebkleveter Yeah, I don't think you can reference `self` because nothing has been initialized yet. It may be possible when initializing an enum or inside a failable initializer 🤔 

The only problem with the extension you listed above is that it creates a dependency between two extensions. We don't allow SwifterSwift extensions to be used inside other SwifterSwift extensions because most people copy & paste the code they need. This means they would have to search through the library to find all the extensions they need 😓

**Comment by BennX** [comment]
@SD10 @calebkleveter @LucianoPAlmeida all of the comments are right. 

People tend to write things like:
```swift
let btn = UIButton()
let sgmt = UISegmentedControl()
let view = UIView()
let stackView = UIStackView(views: [btn, sgmt, view])
```
And we could easily create a variadic convenience constructor. But whenever you have the scenario like in a TableView where you don't know the content of the stack you'll build up an array for it, fill it and convert it into a stack. 

We could also add a variadic constructor and fully skip the adding of `[]` of the users. But I like the `array.stack` too. 
For me the difference between: 
```swift
let stackView = [btn, sgmt, view].stacked()
```
and
```swift
let stackView = UIStackView(views: [btn, sgmt, view])
```
is not that big. I'm fine having just one or both. It's just syntactic sugger. 

A third approach could be a variadic one:

```swift
extension UIStackView {
    public convenience init(orientation: UILayoutConstraintAxis = .horizontal, spacing: CGFloat = 0.0, alignment: UIStackViewAlignment = .fill, distribution: UIStackViewDistribution = .fill, views: UIView ...) {
        self.init(arrangedSubviews: views)
        self.axis = orientation
        self.spacing = spacing
        self.alignment = alignment
        self.distribution = distribution
    }
}
```

We could use it like this:
```swift
let btn = UIButton()
let sgmt = UISegmentedControl()
let view = UIView()
let stackView = UIStackView(views: btn, sgmt, view)
```

However having stacked on a array of UIViews seem to be handy in case someone need's it. If there  is no conclusion in "just have that one extension", we could simply provide all of them.

**Comment by LucianoPAlmeida** [comment]
@BennX For me, the convenience init is the best option for all the reasons that the guys pointed out above :)

**Comment by omaralbeik** [comment]
Hey guys 👋 
`UIStackView` has an initializer to set arranged subviews already [`init(arrangedSubviews:)`](https://developer.apple.com/documentation/uikit/uistackview/1616240-init)

I don't use storyboards, instead, I add my UI elements in code and customize them in closures which gives me a better separation and control over each view properties, like the code below:

```swift
class View: UIView {

	lazy var button: UIButton = {
		let button = UIButton()
		// customize the button
		return button
	}()

	lazy var label1: UILabel = {
		let label1 = UILabel()
		// customize the label
		return label1
	}()

	lazy var label2: UILabel = {
		let label2 = UILabel()
		// customize the label
		return label2
	}()

	lazy var stackView: UIStackView = {
		return [button, label1, label2].stacked()
	}()

}

private extension Array where Element == UIView {

	func stacked(/* argments like axis and others */) -> UIStackView {
		let stackView = UIStackView(arrangedSubviews: self)
		// customize the stackView based on method given arguments
		return stackView
	}

}
```

The `convenience initializer` sounds more like _UIKit_ but when I follow the code example above from top to bottom I think it also makes sense to stack `UIViews` as if they are an array :)

If we decided on adding this as an extension to _Array_, it should NOT be added to the current ArrayExtensions.swift file since it is used in SwiftStd subspec. Maybe we can create another ArrayExtensions.swift file under the `UIKit` subspec with extensions for arrays that has UIKit elements only

Thank you!

**Comment by SD10** [comment]
> but when I follow the code example above from top to bottom I think it also makes sense to stack UIViews as if they are an array :)

These are in an Array too 🤔
```Swift
lazy var stackView: UIStackView = {
	return UIStackView([button, label1, label2])
}()
```
i-was-told-there-would-be-bikeshed
I'm not really bothered by this too much to be honest, but here are my thoughts:

- Feels weird to have an extension on `Array` that is related to UIKit 😂 
- It requires a different project structure
- Increases compile times for your project to resolve the generic constraint

**Comment by omaralbeik** [comment]
@SD10 You got me convinced on your third point, I don't want to make my app compile slower, that's the whole reason why I don't use Storyboards 😉

Anyway, the idea is to set the arranged subviews and properties of a stack view in one line, since `convenience init` is a better fit for SwifterSwift, I totally agree with you 👍

```swift
public extension UIStackView {

	public convenience init(
		arrangedSubviews: [UIView],
		axis: UILayoutConstraintAxis,
		distribution: UIStackViewDistribution = .fill,
		alignment: UIStackViewAlignment = .leading,
		spacing: CGFloat = 0) {

		self.init(arrangedSubviews: arrangedSubviews)

		// set properties here
	}
}
```

**Comment by omaralbeik** [comment]
@BennX Sorry for the inconvenience, could you please refactor the extension into a `convenience init` and add it to a new **`UIStackViewExtensions.swift`** file under the **UIKit** directory :)

**Comment by wdcurry** [comment]
Interesting thread. While i love the time-saving of IB, and the intuitive nature of it, and doubt i would engage the direction of this thread, it is nice to see the effort as an option.

**Comment by BennX** [comment]
@omaralbeik As soon as i have time I'll create a new "clean" PR for that. 👍

**Pull request closed without merging**
