### PR TITLE
Removing shuffle and shuffled equatable Element constraint.

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ ] New extensions are written in Swift 4.
- [ ] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [ ] I have added tests for new extensions, and they passed.
- [ ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ ] All extensions are declared as **public**.

### CODE REVIEW

**Comment by SD10** [comment]
@LucianoPAlmeida I just quickly glanced at the code here. Is this change because we're only comparing indices and not the elements themselves?

**Comment by LucianoPAlmeida** [comment]
Yeap, It does not need the equatable constraint :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omaralbeik** [comment]
Thank you @LucianoPAlmeida for taking care of this 😎

**Comment by SD10** [comment]
Nice catch @LucianoPAlmeida, sorry I missed the response

**Pull request merged**
